#Configuration file for https://circleci.com/gh/udayvunnam/workflows/xng-breadcrumb

# Note: YAML anchors allow an object to be re-used, reducing duplication.
# The ampersand declares an alias for an object, then later the `<<: *name` syntax dereferences it.
# See http://blog.daemonl.com/2016/02/yaml.html.
# To validate changes, use an online parser, eg. http://yaml-online-parser.appspot.com/

# Set default docker image and version
var_1: &docker_image circleci/node:10.12

# Setup a cache key, that restores by checking checksum of package.json.
var_2: &cache_key v1-xng-breadcrumbs-{{ checksum "package.json" }}
var_3: &cache_fallback_key 1-xng-breadcrumbs- # used if checksum fails

# Settings common to each job
var_4: &job_defaults
  working_directory: ~/xng
  docker:
    - image: *docker_image

# Cache the node modules installed
var_5: &restore_cache
  restore_cache:
    keys:
      - *cache_key
      - *cache_fallback_key

# Saves the cache for the current package lock file. We store the node modules
var_6: &save_cache
  save_cache:
    key: *cache_key
    paths:
      - 'node_modules'

# npm install
var_7: &npm_install
  run: npm install

# -----------------------------
# Container version of CircleCI
# -----------------------------
version: 2

# -----------------------------------------------------------------------------------------
# Job definitions. Jobs which are defined just here, will not run automatically. Each job
# must be part of a workflow definition in order to run for PRs and push builds.
# -----------------------------------------------------------------------------------------
jobs:
  build:
    <<: *job_defaults
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - *save_cache
      - run: npm run build
      - run: npm test
  release-library:
    <<: *job_defaults
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - *save_cache
      - run: npm run build
  deploy-app:
    <<: *job_defaults
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - *save_cache
      - run: npm run build
