#Configuration file for https://circleci.com/gh/udayvunnam/workflows/xng-breadcrumb

# Note: YAML anchors allow an object to be re-used, reducing duplication.
# The ampersand declares an alias for an object, then later the `<<: *name` syntax dereferences it.
# See http://blog.daemonl.com/2016/02/yaml.html.
# To validate changes, use an online parser, eg. http://yaml-online-parser.appspot.com/

# Set default docker image and version
var_1: &docker_image circleci/node:10.12
var_2: &browsers_docker_image circleci/node:10.12-browsers

# Setup a cache key, that restores by checking checksum of package.json.
var_3: &cache_key v1-xng-breadcrumbs-{{ checksum "package.json" }}
var_4: &cache_fallback_key 1-xng-breadcrumbs- # used if checksum fails

# Settings common to each job
var_5: &job_defaults
  working_directory: ~/repo
  docker:
    - image: *docker_image

# Cache the node modules installed
var_6: &restore_cache
  restore_cache:
    keys:
      - *cache_key
      - *cache_fallback_key

# Saves the cache for the current package lock file. We store the node modules
var_7: &save_cache
  save_cache:
    key: *cache_key
    paths:
      - 'node_modules'

# npm install
var_8: &npm_install
  run: npm install

# -----------------------------
# Container version of CircleCI
# -----------------------------
version: 2

# -----------------------------------------------------------------------------------------
# Job definitions. Jobs which are defined just here, will not run automatically. Each job
# must be part of a workflow definition in order to run for PRs and push builds.
# -----------------------------------------------------------------------------------------
jobs:
  test:
    <<: *job_defaults
    docker:
      # Needed because tests depend on Chrome being available.
      - image: *browsers_docker_image
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - *save_cache
      - run:
          name: Build Library and App
          command: sudo npm run build
      - run:
          name: Run tests
          command: npm test
      - persist_to_workspace:
          root: ~/repo
          paths: .

  publish:
    <<: *job_defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: npm run publish-lib

workflows:
  version: 2
  test-publish:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
