# Configuration file for https://circleci.com/gh/udayvunnam/workflows/xng-breadcrumb

# Note: YAML anchors allow an object to be re-used, reducing duplication.
# The ampersand declares an alias for an object, then later the `<<: *name` syntax dereferences it.
# See http://blog.daemonl.com/2016/02/yaml.html.
# To validate changes, use an online parser, eg. http://yaml-online-parser.appspot.com/

# Set default docker image and version
var_1: &docker_image circleci/node:10.12
var_2: &browsers_docker_image circleci/node:10.12-browsers

# Setup a cache key, that restores by checking checksum of package.json.
var_3: &cache_key v1-xng-breadcrumb-{{ checksum "package.json" }}
var_4: &cache_fallback_key v1-xng-breadcrumb- # used if checksum fails

# Settings common to each job
var_5: &job_defaults
  working_directory: ~/repo
  docker:
    - image: *docker_image

# Cache the node modules installed
var_6: &restore_cache
  restore_cache:
    keys:
      - *cache_key
      - *cache_fallback_key

# Saves the cache for the current package lock file. We store the node modules
var_7: &save_cache
  save_cache:
    key: *cache_key
    paths:
      - 'node_modules'

# attach saved workspace
var_8: &attach_workspace
  attach_workspace:
    at: ~/repo
# -----------------------------
# Container version of CircleCI
# -----------------------------
version: 2

# -----------------------------------------------------------------------------------------
# Job definitions. Jobs which are defined just here, will not run automatically. Each job
# must be part of a workflow definition in order to run for PRs and push builds.
# -----------------------------------------------------------------------------------------
jobs:
  build:
    <<: *job_defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Install Dependencies
          command: npm install --quiet --no-progress
      - *save_cache
      - run:
          name: Build Library and App
          command: sudo npm run build
      - persist_to_workspace:
          root: ~/repo
          paths: .

  test:
    <<: *job_defaults
    docker:
      - image: *browsers_docker_image # Needed because tests depend on Chrome being available.
    steps:
      - *attach_workspace
      - run:
          name: Run tests
          command: npm test

  release:
    <<: *job_defaults
    steps:
      - *attach_workspace
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Authenticate with github
          command: git config user.email "uday4vunnam@gmail.com" && git config user.name "udayvunnam"
      - run:
          name: Authorize github
          command: git remote rm origin && git remote add origin https://udayvunnam:$GH_TOKEN@github.com/udayvunnam/xng-breadcrumb.git
      - run:
          name: semantic version
          command: npm run version
      - run:
          name: publish library
          command: npm run publish:lib

  deploy:
    <<: *job_defaults
    steps:
      - *attach_workspace
      - run:
          name: Netlify Deploy
          command: ./node_modules/.bin/netlify deploy --prod --dir=dist/xng-breadcrumb-app

workflows:
  version: 2
  build-test-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - test
          filters:
            tags:
              only: /.*/ # runs for no branches and only for tags starting with 'v'
            branches:
              only: master
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              only: master
